### PR TITLE
2.3 compatability

### PR DESCRIPTION
**Pull request by loremipson**
I've updated the field with necessary changes to work in Symphony 2.3 / Members 1.2RC2. So far, so good in my testing.

### CODE REVIEW

**Comment by acreek** [comment]
I tried to implement with Symphony 2.3 / Members 1.2RC2 and I don't seem to be able to get any xml output for the field-id. Have you noticed this?

**Comment by loremipson** [comment]
Sorry, I didn't realize this had a reply notification.

I haven't noticed that, but I'll look into it. I'll be using this again soon for another project and I'll double check it. It's likely I overlooked something.

**Comment by michael-e** [comment]
Bump. Any news on this issue?

**Comment by loremipson** [comment]
Wow. I'm really bad at getting notices here.

I just added this to another project I'm building (Symphony 2.3.1 and Members 1.2) and it seems to be working just fine. I get the `event` xml output, adding or removing the user association as expected. I know this is several months old now, but are  you still having issues with it?

**Comment by brendo** [comment]
I've setup an integration branch for this extension and have merged the changes by @Implemint and added some additional updates. All future PR's should go to the `integration` branch :) Thanks!

**Pull request closed without merging**
